# Generated by Django 5.0.2 on 2024-02-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Катеогия',
                'verbose_name_plural': 'Категории',
                'db_table': 'catrgory',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, verbose_name='Жанр')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Статус')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=50, verbose_name='Студия')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'db_table': 'studio',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('alt_title', models.CharField(max_length=100, verbose_name='Альтернативное название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_aired', models.DateField(verbose_name='Дата выхода')),
                ('duration', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('quality', models.CharField(max_length=50, verbose_name='Качество')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='anime_covers/%Y/%m', verbose_name='Обложка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(related_name='anime_genre', to='anime.genre', verbose_name='Жанр')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.status', verbose_name='Статус')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.studio', verbose_name='Студия')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'db_table': 'anime',
            },
        ),
    ]
