# Generated by Django 5.0.2 on 2024-02-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_animeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeseries',
            name='series_frame',
            field=models.ImageField(blank=True, null=True, upload_to='anime_series/frames/%Y', verbose_name='Кадры'),
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='anime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_series', to='anime.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='animeseries',
            name='series_file',
            field=models.FileField(upload_to='anime_series/%Y/%m', verbose_name='Серии'),
        ),
    ]
